# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-23 03:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='\u516c\u53f8\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='NodeRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('included_nodes', models.CharField(blank=True, max_length=500, verbose_name='\u5305\u542b\u7684\u8282\u70b9')),
                ('relations', models.TextField(blank=True, verbose_name='\u8282\u70b9\u5173\u7cfb')),
            ],
        ),
        migrations.CreateModel(
            name='WorkNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_desp', models.CharField(blank=True, max_length=300, verbose_name='\u7b80\u7565\u63cf\u8ff0')),
                ('long_desp', models.TextField(blank=True, verbose_name='\u8be6\u7ec6\u63cf\u8ff0')),
                ('status', models.CharField(choices=[('waiting', '\u7b49\u5f85'), ('working', '\u5904\u7406\u4e2d'), ('finish', '\u5b8c\u6210')], default='waiting', max_length=30, verbose_name='\u72b6\u6001')),
                ('mtime', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
            ],
        ),
    ]
