# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-24 10:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('liucheng', '0003_remove_nodegroup_included_nodes'),
    ]

    operations = [
        migrations.AddField(
            model_name='worknode',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='liucheng.BusClient', verbose_name='\u5ba2\u6237'),
        ),
        migrations.AlterField(
            model_name='busclient',
            name='name',
            field=models.CharField(blank=True, max_length=200, verbose_name='\u5ba2\u6237\u540d\u79f0'),
        ),
    ]
