# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-25 02:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('liucheng', '0004_auto_20170824_1831'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worknode',
            name='client',
        ),
        migrations.AddField(
            model_name='nodegroup',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='liucheng.BusClient', verbose_name='\u5ba2\u6237'),
        ),
        migrations.AddField(
            model_name='nodegroup',
            name='kind',
            field=models.CharField(choices=[('workrecord', '\u8bb0\u5f55'), ('template', '\u6a21\u677f')], default='workrecord', max_length=30, verbose_name='\u7c7b\u578b'),
        ),
        migrations.AddField(
            model_name='nodegroup',
            name='long_desp',
            field=models.TextField(blank=True, verbose_name='\u8be6\u7ec6\u63cf\u8ff0'),
        ),
        migrations.AddField(
            model_name='nodegroup',
            name='short_desp',
            field=models.CharField(blank=True, max_length=300, verbose_name='\u7b80\u7565\u63cf\u8ff0'),
        ),
        migrations.AddField(
            model_name='worknode',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 8, 25, 2, 40, 57, 275000, tzinfo=utc), verbose_name='\u521b\u5efa\u65f6\u95f4'),
            preserve_default=False,
        ),
    ]
