# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-08-28 01:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc
import helpers.base.jsonfield


class Migration(migrations.Migration):

    dependencies = [
        ('liucheng', '0006_auto_20170827_0045'),
    ]

    operations = [
        migrations.AddField(
            model_name='nodegroup',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2017, 8, 28, 1, 30, 11, 620000, tzinfo=utc), verbose_name='\u521b\u5efa\u65f6\u95f4'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nodegroup',
            name='relations',
            field=helpers.base.jsonfield.JsonField(default=[], verbose_name='\u8282\u70b9\u5173\u7cfb'),
        ),
    ]
