# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-08-30 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liucheng', '0008_auto_20170830_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nodegroup',
            name='start_time',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='\u5f00\u59cb\u65f6\u95f4'),
            preserve_default=False,
        ),
    ]
