# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-03 04:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organize', '0013_auto_20170823_1127'),
        ('liucheng', '0010_nodegroup_related_emp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nodegroup',
            name='related_emp',
        ),
        migrations.AddField(
            model_name='worknode',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organize.Employee', verbose_name='\u8d1f\u8d23\u4eba'),
        ),
    ]
