# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-13 14:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('liucheng', '0013_auto_20170913_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='busclient',
            name='name',
            field=models.CharField(max_length=200, unique=True, verbose_name='\u5ba2\u6237\u540d\u79f0'),
        ),
    ]
