# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-17 10:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import helpers.base.jsonfield


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organize', '0013_auto_20170823_1127'),
    ]

    operations = [
        migrations.CreateModel(
            name='BusClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='\u5ba2\u6237\u540d\u79f0')),
            ],
        ),
        migrations.CreateModel(
            name='WorkGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relations', helpers.base.jsonfield.JsonField(default=[], verbose_name='\u6d41\u7a0b\u56fe')),
                ('short_desp', models.CharField(blank=True, max_length=300, verbose_name='\u7b80\u7565\u63cf\u8ff0')),
                ('long_desp', models.TextField(blank=True, verbose_name='\u8be6\u7ec6\u63cf\u8ff0')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workboard.BusClient', verbose_name='\u5ba2\u6237')),
            ],
        ),
        migrations.CreateModel(
            name='WorkNode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_desp', models.CharField(blank=True, max_length=300, verbose_name='\u7b80\u7565\u63cf\u8ff0')),
                ('long_desp', models.TextField(blank=True, verbose_name='\u8be6\u7ec6\u63cf\u8ff0')),
                ('status', models.CharField(choices=[('waiting', '\u7b49\u5f85'), ('finish', '\u5b8c\u6210')], default='waiting', max_length=30, verbose_name='\u72b6\u6001')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='\u521b\u5efa\u65f6\u95f4')),
                ('mtime', models.DateTimeField(auto_now=True, verbose_name='\u4fee\u6539\u65f6\u95f4')),
                ('start_time', models.CharField(blank=True, max_length=20, verbose_name='\u542f\u52a8\u65f6\u95f4')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_nodes', to='organize.Employee', verbose_name='\u8d1f\u8d23\u4eba')),
                ('work_group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workboard.WorkGroup', verbose_name='\u8282\u70b9\u7ec4')),
            ],
        ),
    ]
