# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-09-17 13:08
from __future__ import unicode_literals

from django.db import migrations
import helpers.base.jsonfield


class Migration(migrations.Migration):

    dependencies = [
        ('workboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workgroup',
            name='relations',
        ),
        migrations.AddField(
            model_name='workgroup',
            name='order',
            field=helpers.base.jsonfield.JsonField(blank=True, default=[], verbose_name='\u8fdb\u5ea6\u8be6\u60c5'),
        ),
    ]
