# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2017-09-22 06:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import helpers.base.jsonfield


class Migration(migrations.Migration):

    dependencies = [
        ('workboard', '0003_auto_20170921_0001'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkTemplate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_desp', models.CharField(blank=True, max_length=300, verbose_name='\u7b80\u7565\u63cf\u8ff0')),
                ('long_desp', models.TextField(blank=True, verbose_name='\u8be6\u7ec6\u63cf\u8ff0')),
                ('content', helpers.base.jsonfield.JsonField(blank=True, default={}, verbose_name='\u5185\u5bb9')),
            ],
        ),
        migrations.AlterModelOptions(
            name='busclient',
            options={'verbose_name': '\u5ba2\u6237\u4fe1\u606f\u8868'},
        ),
        migrations.AlterModelOptions(
            name='workgroup',
            options={'verbose_name': '\u5de5\u4f5c\u6d41\u7a0b\u8868'},
        ),
        migrations.AlterModelOptions(
            name='worknode',
            options={'verbose_name': '\u5de5\u4f5c\u6b65\u9aa4\u8868'},
        ),
        migrations.AlterField(
            model_name='worknode',
            name='work_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='workboard.WorkGroup', verbose_name='\u5de5\u4f5c\u6d41\u7a0b'),
        ),
    ]
